// <auto-generated />
using System;
using ControlePressao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlePressao.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250706180910_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ControlePressao.Models.Glicose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Glicose");
                });

            modelBuilder.Entity("ControlePressao.Models.Pressao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("Diastolica")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrequenciaCardiaca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sistolica")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pressao");
                });
#pragma warning restore 612, 618
        }
    }
}
